### PR TITLE
fix: check kernel module `dm_crypt` on host machines

### PR DESCRIPTION
**Pull request by mantissahz**
#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#9153

#### What this PR does / why we need it:
- check if the module `dm_crypt` is enabled
- enable the module `dm_crypt`

### CODE REVIEW

**Review by derekbit — DISMISSED** [review]
LGTM

**Comment by derekbit** [comment]
@mantissahz after resolving the commit-lint error, we can merge it.

**Comment by derekbit** [comment]
@mantissahz Could you resolve the conflicts?

**Review by derekbit — APPROVED** [review]

**Comment by mantissahz** [comment]
@Mergifyio backport v1.7.x

**Pull request merged**
